# backend/config.py

EXCHANGE = "kraken"

SYMBOLS = [
    "BTC/USDT", "ETH/USDT", "SOL/USDT", "BNB/USDT",
    "XRP/USDT", "ADA/USDT", "DOGE/USDT", "AVAX/USDT",
    "LINK/USDT", "MATIC/USDT"
]

TIMEFRAMES = ["15m", "1h"]

EMA_PERIODS = [20, 50, 100, 200]

STOCH_RSI_PERIOD = 14

TELEGRAM_BOT_TOKEN = "YOUR_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"

SCAN_INTERVAL_SECONDS = 30
